### ISSUE TITLE
[7월 2주차] 질문 주제 - Spring

### ISSUE THREAD

**Issue by meoldae** [SSAFY-9th-6-Study/CS-Study#54]

**Comment by cksghks89** [comment]
### 스프링 질문
1. DI 가 무엇인지 설명해주세요. -> DI를 적용하기 위한 3가지 방법에 대해 말해보세요.
2. AOP 란 무엇인지 설명해 보세요.
3. 스프링 빈에 대해 아는대로 설명해보세요.
4. 필터와 인터셉터의 차이점에 대해 설명해보세요. -> 필터와 인터셉터의 사용 예시를 설명해주세요.
5. 스프링부트의 장점에 대해 얘기해 보세요.

**Comment by meoldae** [comment]
1. ```@ModelAttribute``` 와 ```@RequestBody```의 차이에 대해 알고있나요?
  1-1) 두 어노테이션이 객체 필드에 전송한 값을 어떻게 바인딩하나요?

2. ```Bean```의 생명주기에 대해 설명해주세요.

3. Spring MVC의 흐름에 대해 설명해보세요.
  
4. ```IoC```에 대해 설명해보세요.
  4-1) 객체의 제어는 누가 하나요?

5. Spring에서 ```CORS``` 에러를 해결하기 위한 방법을 설명해보세요.

**Comment by Brojjun** [comment]
1. Spring에서 가장 인상깊은 기능에 대해 말해보세요

2. Java의 Servlet과 spring의 차이를 말해보세요

3. Mybatise와 JPA의 차이를 설명해보세요 ( 직접적이지는 않지만, 나올 수 있다고 생각해서 )

4. MAVEN과 GRADLE의 차이를 설명해보세요

5. 자소서에 적혀있는 SPRING 프로젝트에 대해 설명해보세요

스프링에 대한 질문은 많아보여 스프링에 간접적으로 연관이 있는 질문들을 준비해봤습니다.

**Comment by pockypepe** [comment]
1. spring을 사용함으로 개발자가 얻는 장점에 대해 설명해주세요.
2. spring에서 MVC 모델의 요청 흐름에 대해 간략하게 설명해주세요.
3. aop에 대해 설명해주세요
4. ioc에 대해 설명해주세요

**Comment by Devwooki** [comment]
1. Spring Bean 이란 무엇인지 어떤 역할을 수행하는지 아만큼 설명해 주세요
 1-1. 그럼 IOC와 DI에 대해 설명해주실 수 있을까요?

2. `@RequestParam`과 `@RequestBody`에 대해 설명해주세요.
3. MVC패턴에 대해 설명해 주세요.
  3-1. Spring에서 MVC패
5. Spring의 핵심모듈에 대해 아는 것이 있다면 2가지 정도만 설명해주세요.
6. Spring프로젝트에서 웹 애플리케이션 구성을 커스터 마이징 하기 위해선 어떤 작업을 수행해야할까요?
 6-1. 해당 작업을 수행한 경험이 있다면 간략히 설명 부탁드리겠습니다.
