### ISSUE TITLE
[7월 5주차] 질문 주제 - DB

### ISSUE THREAD

**Issue by meoldae** [SSAFY-9th-6-Study/CS-Study#56]

**Comment by Brojjun** [comment]
1. 정규화나 반정규화를 해본 사례를 말씀해보세요

2. 인덱스를 사용해서 최적화를 해본적이 있나요?

3. RDBMS vs NoSQL 의 차이와 장단점을 말해보세요

4. JPA를 쓰셨다고 했는데, JPA에서는 데이터베이스의 JOIN을 어떻게 처리하나요?

5. N+1 문제와 해결하신 경험이 있다면 설명해주세요

**Comment by cksghks89** [comment]
1. SQL의 쿼리 수행 순서에 대해 말해보세요.
2. RDBMS의 트리거(Trigger)에 대해 아는대로 설명해보세요.
3. 정규화의 특징과 정규형의 각 단계와 특징을 아는대로 말해보세요.
4. 트랜잭션이의 특징 트랜잭션의 격리 수준에 대해 말해보세요.
5. 데이터베이스의 무결성이란 무엇인지 말해보세요.

**Comment by meoldae** [comment]
1. ConnectionPool에 대해 설명해주세요.
2. INDEX에 대해 설명해주세요.
  2-1. 자료형으로는 무엇을 사용하나요?
3. ACID란 무엇인가요?
4. NoSQL에 대해 예시를 들어 설명해주세요.

**Comment by Devwooki** [comment]
1. 정규화를 수행할 경우 어떤 장단점이 있는지 아는대로 말씀해주세요.
2. 이상현상에 대한 종류와 
3. 엘라스틱 서치와 RDBMS의 LIKE 검색의 차이에 대해 설명해주세요
4. inner join과 outer 조인의 차이에 대해 알고계신다면 설명 부탁드리겠습니다.
 - 4번 꼬리질문? join의 on과 where절의 차이를 설명해주시겠어요?
5. DB clustering과 Replication에 차이를 설명해주실 수 있나요?
