### ISSUE TITLE
[8월 1주차] 질문 주제 - Network

### ISSUE THREAD

**Issue by meoldae** [SSAFY-9th-6-Study/CS-Study#58]

**Comment by Brojjun** [comment]
1. 당신의 컴퓨터에서 WWW.NAVER.COM 을 입력했을 때 일어나는 일을 최대한 자세히 설명해주세요

2. 자기소개서에 WebSocket내용이 있는데, WebSocket과 http 프로토콜을 비교하여 설명해주세요

3. http 프로토콜에 대해 최대한 자세히 설명해주세요

4. 가장 인상깊은 프로토콜과 그 이유에 대해 설명해주세요

5. tcp에서 연결을 할때는 3way, 끊을 때는 4way인데 왜 다르게 동작하는지 설명해주세요

**Comment by meoldae** [comment]
1. http와 https 의 차이점에 대해 말씀해주세요.

2. http의 특성이 뭔지 설명해주세요.
   2-1. stateless와 connectionless에 대해 설명해주세요.
  
3. REST API란 무엇인가요?

4. HTTP Method에 대해 아는대로 말씀해주세요.

5. Http Status Code에 대해 설명해주세요.

**Comment by Devwooki** [comment]
1. polling고 websocket의 차이에 대해 말씀해 주세요.
2. `RESTful하다`가 어떤건지 말씀해주세요
3. JWT를 사용해 인증관리를 하셨다고 했는데 왜 그런 방식을 사용한건지 궁금합니다.
 - JWT를 활용한 사용자 인증 프로세스에 대해 최대한 자세하게 설명 부탁드리겠습니다.
4. CORS를 알고 있나요? 개념과 어떻게 해결했는지 궁금합니다.
 - CORS를 발생시키는 원인에 대해 말씀해 주세요
5. 스위치와 허브에 대해 각각 설명하고 차이점을 말씀해주세요

**Comment by cksghks89** [comment]
1. OSI 7계층에 대해 간략히 설명해주세요.

2. 채팅 서버-클라이언트간에는 TCP와 UDP중 어떤 프로토콜을 사용하는 것이 좋을지에 대해 가능한 구체적으로 설명해주세요..

3. HTTP 1.1 의 keep alive 기능에 대해 간략히 설명해 주세요.

4. 쿠키와 세션의 차이점에 대해 간략히 설명해주세요.

5. 웹브라우저를 실행시켜서 주소창에 특정 URL 값을 입력시킨 후, 엔터를 눌렀을 때, 페이지가 렌더링되는 과정을 웹통신 흐름에 중점을 두어 가능한 구체적으로 설명해주세요.

**Comment by pockypepe** [comment]
1. Tcp와 udp의 차이점에 대해 설명해 보세요. 
2. Tcp의 신뢰성을 보장하는 방법을 설명해 보세요
3. Restful이란 무엇인가요
4. Http와 https의 차이점에 대해 설명해 보세요
5. 대칭키, 비대칭키 암호화 방식에 대해 설명해 보세요
