### ISSUE TITLE
[8월 2주차] 질문 주제 - 자료구조

### ISSUE THREAD

**Issue by cksghks89** [SSAFY-9th-6-Study/CS-Study#60]

**Comment by Brojjun** [comment]
1. 레드블랙트리에 대해 말해보세요 ( DB )
2. 세그먼트 트리에 대해 말해보세요
3. 링크드리스트와 배열의 차이에 대해 말해보세요 ( 질문자의 의도 : 배열의 주소 연속성에 대해 알고있는지 => 캐싱에 대해 알고있는지 )
4. 자바를 주 언어로 쓰신다고 들었는데 자바에서 해쉬맵이 어떤식으로 구현되어 있는지 설명해보세요
5. 자바에서 어레이리스트와 링크드리스트의 차이를 설명해주세여

**Comment by meoldae** [comment]
1. Stack, Queue의 실제 사용 예시를 들어 설명해주세요.
2. Binary Search Tree와 Binary Tree 에 대해 설명해주세요.
3. Thread - Safe 한 자료구조에 대해 예시와 함께 설명해주세요.
4. Java의 Collection Framework에 대해 설명해주세요.

**Comment by cksghks89** [comment]
1. Stack, Queue, Tree, Heap의 구조에 대해서 설명해주세요.
2. Array와 LinkedList의 구조와 장/단점에 대해서 설명해보세요.
3. 해시테이블과 시간복잡도에 대해 설명해주세요.
4. 본인이 생각하는 자료구조란 무엇인지 말해보세요.
5. 이진탐색트리(BST) 와 이진트리 (BT)의 차이점에 대해 설명해보세요.

**Comment by Devwooki** [comment]
1. 인접 리스트와 인접 행렬의 차이에 대해 설명해주세요.
 - 어떤 상황 등에 사용하면 유리할지 등
2. JAVA를 주로 사용하셨다고 했는데 ArrayList와 LinkedList의 차이를 알고 계신가요?
3. Java Collection의 Comparable, Comparator의 차이에 대해 듣고 싶습니다.
4. Deque라는 자료구조는 Stack과 Queue의 성질을 모두 가지고 있는데 그럼에도 불구하고 Deque보다 Stack, Queue를 주로 사용하는 이유

**Comment by pockypepe** [comment]
1. 배열과 연결 리스트의 차이점은 무엇인가요?
2. Hash Map과 Hash Table의 차이점에 대해 설명해주세요.
3. 클래스와 구조체의 차이점을 설명하고, 어떤 상황에서 어떤 것을 선택해야 할까요?
4. 그래프의 종류와 그래프 탐색 알고리즘에 대해 이야기해보세요.
5. 스택 오버플로와 큐 언더플로우가 무엇인지, 어떻게 방지할 수 있나요?
