### ISSUE TITLE
[9월 2주차] 질문 주제 - 운영체제

### ISSUE THREAD

**Issue by meoldae** [SSAFY-9th-6-Study/CS-Study#62]

**Comment by meoldae** [comment]
### 1. 멀티프로세싱과 멀티스레딩의 차이에 대해 말씀해주세요.
 
### 2. 동기와 비동기의 차이에 대해 말씀해주세요.

### 3. DeadLock에 대해 말씀해주세요.

### 4. 페이징이 무엇인지 알고 있나요? 아는대로 설명해주세요.

**Comment by cksghks89** [comment]
### 1. 내부 단편화와 외부 단편화에 대해 설명해보세요.
### 2. 인터럽트가 발생했을 때 처리되는 과정에 대해 설명해보세요.
### 3. 캐시 메모리에 대해 설명하고, locality 의 특징에 대해 설명해주세요.
### 4. 데드락의 4가지 필요조건에 대해 설명해주세요

**Comment by Brojjun** [comment]
**세마포어, 뮤텍스에 대해서 설명해주세요

멀티스레드를 사용하는 이유가 뭔가요?

기아상태와 기아상태를 막는 방법을 설명해주세요

프로그램 실행 시 메모리에 생기는 4가지 영역과 각 영역이 저장하는 데이터의 종류에 대해 설명해주세요**

**Comment by pockypepe** [comment]
1. 메모리의 구조를 영역에 따라서 설명하시오
2. 메모리의 힙 영역과 스택 영역의 차이에 대해 설명해보세요
3. 데드락(Deadlock)이란 무엇이며, 어떻게 방지할 수 있나요?
4. 가상 메모리(Virtual Memory)는 무엇이며, 어떻게 동작하나요?
5. 프로세스 상태(States)에 대해 설명해주세요.

**Comment by Devwooki** [comment]
1. 커널이 무엇인지 설명해주실 수 있나요?
2. 그렇다면 메모리의 구조 영역이 어떻게 되는지 설명해주세요
4. 크롬 브라우저에서 한 탭에 오류가 생기더라도, 다른 탭에 영향을 끼치지 않습니다. 그렇다면 각각의 크롬 탭은 프로세스일까요? 쓰레드일까요?
