### ISSUE TITLE
[9월 3주차] 질문 주제 - 운영체제

### ISSUE THREAD

**Issue by meoldae** [SSAFY-9th-6-Study/CS-Study#64]

**Comment by pockypepe** [comment]
1. 페이징에 대해 설명해주시고, 장단점을 설명해주세요
2. 멀티 쓰레드 환경에서의 주의해야 할 점에 대해 설명할 수 있나요?
3. 동시성과 병렬성이 어떻게 다른지 설명해주세요.
4. Thrashing(쓰레싱)에 대해 설명해주세요.

**Comment by meoldae** [comment]
1. 동기와 비동기의 차이에 대해 말씀해주세요.
2. 프로세스의 라이프사이클에 대해 설명해주세요.
3. 리눅스 (Linux) 기반의 파일 시스템에 대해 설명해주세요.
4. CPU 스케쥴링에 대해 아는대로 설명해주세요.

**Comment by Devwooki** [comment]
1. 스케쥴러의 종류에 대해 말씀해주세요
2. 동기, 비동기를 이용한 경험이 있다면 말씀해주세요(키워드, 사용한 이유 등)
3. 데드락이 무엇이고 데드락 발생 조건에 대해 알고 계신것이 있다면 함께 말씀해주세요
4. 서버 운영체제는 왜 대부분 CLI를 다루는지 견해를 듣고 싶습니다.

**Comment by cksghks89** [comment]
1. Blocking과 Non-Blocking 에 대해 설명해주세요.
2. 다음 프로세스의 종류에 대해 아는대로 설명해보세요. (데몬 프로세스, 좀비 프로세스, 고아 프로세스, 자식 프로세스)
3. 시스템콜이 무엇인지 예시를 들어 아는대로 설명해보세요.
4. OS의 역할 중 하나는 메모리를 관리하는 것입니다. 그렇다면 메모리 관리를 위해 어떤 전략을 사용하는지 설명해보세요.
5. 메모리의 fit 종류 4가지를 설명해 주세요.

**Comment by Brojjun** [comment]
1. 우분투 운영체제를 사용하셨던데, 왜 많은 리눅스 운영체제 중에 우분투를 사용하셨나요?, 그리고 평소 운영체제를 고르실 때 주의깊게 보는 것이 따로 있나요?
2. "식사하는 철학자 문제"를 에서 데드락이 발생할 수 있는 상황을 설명하고, 어떻게 해결할지 말씀해주세요
"다섯 명의 철학자가 원탁에 앉아 있고, 각자의 앞에는 스파게티가 있고 양옆에 포크가 하나씩 있다.(두 사람 가운데 공유하는 하나의 포크) 그리고 각각의 철학자는 다른 철학자에게 말을 할 수 없다. 이때 철학자가 스파게티를 먹기 위해서는 양 옆의 포크를 동시에 들어야 한다."

2문제만 적겠습니다.
